[versions] # also check project root build.gradle.kts for versions
libVersion = "1.6.0"
compileSdk = "34"
minSdk = "21"
java = "11"
androidx-animation = "1.6.7"
androidx-foundation = "1.6.7"
androidx-appcompat = "1.7.0"
androidx-coreKtx = "1.13.1"
androidxActivityVer = "1.9.0"
androidGradlePlugin = "8.2.2"
junit = "4.13.2"
junitJupiterEngine = "5.10.1"
junitJupiterApi = "5.10.1"
kotlin = "2.0.0"
lifecycleRuntimeKtx = "2.8.1"
material = "1.6.7"
kotlinxCoroutinesCore = "1.8.1"
moleculeRuntime = "2.0.0"
savedstateKtx = "1.2.1"
spotless = "6.25.0"
jetbrainsComposePlugin = "1.6.10"
skiko = "0.8.4"
koin = "3.6.0-Beta4"
uuid = "0.8.4"
webpackCliVersion = "5.1.4"
nodeVersion = "20.14.0"
ktlint = "0.50.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivityVer" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityVer" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstateKtx" }
animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-animation" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-foundation" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "moleculeRuntime" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
skiko-js = { module = "org.jetbrains.skiko:skiko-js-wasm-runtime", version.ref = "skiko" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version = "3.6.0-wasm-alpha2" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsComposePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }